#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "Activating virtenv"
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/GIS/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/GIS/manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/GIS/manage.py collectstatic --noinput --ignore rest_framework'"
python "$OPENSHIFT_REPO_DIR"wsgi/GIS/manage.py collectstatic --noinput --ignore rest_framework

#echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/GIS/manage.py loaddata cafe.json"
#python "$OPENSHIFT_REPO_DIR"wsgi/GIS/manage.py loaddata cafe.json