# .travis.yml
branches:
  only:
    - master
    - openshift  # FIXME remove at merging.

deploy:
  provider: openshift
  user: d.yantsen@gmail.com
  password:
    secure: S7AKoTe3TGeDJ2ffUwy18jbWoTEX47ZOC95KQgOKny3OYjUvESqje80SfBduyVxiLPJsZILIL/8IluhBuJ+zBbcM/DGDPS9y/rOLoCF1B9JWxSS2xccD6EgEOWTIS0c/yzPb3kGw+kqLa0qi9Oq4bIs671+S6EEkxQSkAyZkIfw=
  app: cafegis
  domain: vmigisdevils
  on:
    repo: GISDevils/GisProject
    branch: openshift

language: python

before_script:
  - mysql -e 'create database gis;'

python:
  - "2.7"

env:
  - DJANGO=1.5

install:
  - pip install -r wsgi/GIS/requirements.txt

script:
  - python wsgi/GIS/manage.py test
