# .travis.yml
branches:
  only:
    - master
    - backend  # FIXME remove at merging.

install:
  - bundle install

before_script:
  - mysql --user='travis' --password='' < ./database/database.sql

script: ruby ./database/parser.rb
