# .travis.yml
branches:
  only:
    - master
    - openshift  # FIXME remove at merging.

deploy:
  provider: openshift
  user: "d.yantsen@gmail.com"
  password: "iHowO01n1F"
  domain: "vmigisdevils"
  app: "cafegis"
  on: openshift

language: python

before_script:
  - mysql -e 'create database gis;'

python:
  - "2.7"

env:
  - DJANGO=1.5

install:
  - pip install -r wsgi/GIS/requirements.txt

script:
  - python wsgi/GIS/manage.py test
